--- #YAML:1.0
name:                Net-FTP-Throttle
version:             0.32
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Algorithm::TokenBucket:        0
    Net::FTP:                      2.75
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Leon Brocard <acme@astray.com>
